apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "default-chart.fullname" . }}
data:
  appsettings.Production.json: |
    {
      "Authentication": {
          "Authority": "{{ .Values.connectionStrings.identity }}"
      },
      "Kafka": {
          "bootstrap": {
              "servers": "{{ .Values.kafka.bootstrapServer }}"
          },
          "sasl": {
              "mechanism": "{{.Values.kafka.security.mechanism}}",
              "username": "{{ .Values.kafka.userName }}"
          },
          "security": {
               "protocol": "{{.Values.kafka.security.protocol}}"
          },
          "GroupId": "{{ .Values.kafka.groupid }}"
      },
      "Mongo": {
        "DbName": "{{ .Values.mongoDatabase }}"
      }
    }