apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "default-chart.fullname" . }}
  labels:
    app: {{ template "default-chart.name" . }}
    chart: {{ template "default-chart.chart" . }}
    release: {{ .Release.Name }}

  annotations:
 
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "default-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "default-chart.name" . }}
     
        release: {{ .Release.Name }}
      annotations:

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              release: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
      volumes:
        - name: config
          configMap:
            name: {{ template "default-chart.fullname" . }}
        - name: data
          emptyDir:
            sizeLimit: 100Mi
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: Kafka__sasl__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kafka.userName }}
                  key: password
            - name: ConnectionStrings__Mongo
              valueFrom:
                secretKeyRef:
                  name: mongo-cs
                  key: MongoRWConnectionString
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
            - name: data
              mountPath: /app/data
              readOnly: false
          resources:
        - name: "{{ .Chart.Name }}-test-server"
          image: "{{ .Values.image.repositoryTestServer }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}

