{{- if .Values.ingress.enabled }}
{{- $fullName := include "default-chart.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "default-chart.name" . }}
    chart: {{ template "default-chart.chart" . }}
    release: {{ .Release.Name }}
 
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
spec:
  {{- if .Values.ingress.host }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: tls-{{ .Release.Name }}-ingress
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
{{- end }}