apiVersion: v1
kind: Service
metadata:
  name: {{ template "default-chart.fullname" . }}
  labels:
    app: {{ template "default-chart.name" . }}
    chart: {{ template "default-chart.chart" . }}
    release: {{ .Release.Name }}
 
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "default-chart.name" . }}
    release: {{ .Release.Name }}
